/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package symbolic;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ONEARGFUNCTION = 11;
  /** RegularExpression Id. */
  int PI = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int INUM = 16;
  /** RegularExpression Id. */
  int DNUM = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "<ONEARGFUNCTION>",
    "\"pi\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INUM>",
    "<DNUM>",
  };

}
